### ISSUE TITLE
Incorrect delimiter for imports in sub-directories

### ISSUE THREAD

**Issue by vsa** [MarcDiethelm/grunt-less-imports#16]
When collecting LESS files from sub-directories, backslashes are used as path delimiter (at least on Windows). Example output:
```less
@import (once) "sub\b.less";
```

While LESS itself doesn't seem to care, this does not conform to the CSS specification and causes some other tools to interpret the backslash as escape character instead of a URI delimiter. A forward slash "/" should be generated on all platforms, including Windows.

References:
1) http://www.w3.org/TR/css3-cascade/#at-ruledef-import
2) http://www.w3.org/TR/css3-values/#url-value
3) http://www.ietf.org/rfc/rfc3986

**Comment by vsa** [comment]
Is there any chance to get this resolved? Right now I have to work around the issue. Can I help you out somehow?

**Comment by MarcDiethelm** [comment]
Please let me apologize for the extremely delayed reply. I was on an extended sabbatical and did not look at any code for a very long time. I just now tested and confirmed the bug on a Windows machine. I was able to fix it easily fortunately, without adding a dependency. The solution was to use `path.posix.relative()` instead of `path.relative`, which effectively makes sure that no backslashes are used when creating the URI. If you're still interested in this please upgrade and test version 1.2.0 and let me know if there are any problems.

**Comment by vsa** [comment]
This works fine now, thank you very much.
